### ISSUE TITLE
##[error]Cannot read property '0' of null

### ISSUE THREAD

**Issue by paales** [dorshinar/get-deployment-url#1]
I was working on something similar, and stumbled upon this repo by accident, what a happy accident!

Running into an issue though

```
Run dorshinar/get-deployment-url@v1.0.3
##[error]Cannot read property '0' of null
```

If I rerun the action it will succeed and will return the proper URL.

**Comment by paales** [comment]
![Schermafbeelding 2020-05-10 om 17 08 35](https://user-images.githubusercontent.com/1244416/81502864-ecb78080-92e0-11ea-840d-350e47f34b8b.png)

This was the output of the query, not sure where the error is exactly happening.

If I wait a while I get this response:
![Schermafbeelding 2020-05-10 om 17 09 25](https://user-images.githubusercontent.com/1244416/81502881-05c03180-92e1-11ea-804e-bc0ff0c6d48e.png)

If I then rerun the job, everything works as expected.

**Comment by dorshinar** [comment]
Thanks for taking the time to write an issue!

The output looks fine (on the first run it will detect the `null` environment and just keep querying GitHub's API until it finds something). However it seems like the problem stems from the lack of `edges` on the `deployments` field. 

I've pushed a new release (v1.0.4) which I hope will fix your issue. 
Keep me posted!

**Comment by paales** [comment]
Hmm, still running into the same issue, lemme create a fork an see if I can fix it my self, will create a pr.

**Comment by paales** [comment]
```
 Run dorshinar/get-deployment-url@v1.0.40s
##[error]Cannot read property '0' of null
Run dorshinar/get-deployment-url@v1.0.4
  with:
    token: ***
    retryInterval: 10000
##[error]Cannot read property '0' of null
```

**Comment by paales** [comment]
I think lodash-es/get will only check for undefined, not for null

**Comment by JannikZed** [comment]
hey guys, I'm facing the exact same issue. I'm coming from Gitlab, so no experience with Github actions ... my use-case is a deployment to vercel and later on a lighthouse checking against the deployed URL.

**Comment by sarahatwork** [comment]
I am hitting this issue with a Vercel deployment as well

**Comment by Spaceface16518** [comment]
This is happening to me too, again with a Vercel deployment.

I'm using `v1.0.4`.

> If I then rerun the job, everything works as expected.

This workaround works for me as well.

**Comment by dorshinar** [comment]
Hi!
I've merged #3 , thanks to @paales !
Hopefully this should solve all of your problems. I couldn't replicate the problem (although I'm using Vercel as well), but I believe it could come from running the action too early, before Vercel has a chance to create the deployment in GitHub's API, resulting in a null object. 

Please try `v1.0.5`, and let me know if it fixes your issues.

**Comment by JannikZed** [comment]
It's working for me now! Thank you very much.

**Comment by sarahatwork** [comment]
It works, thanks!

**Comment by dorshinar** [comment]
Glad to hear!
I'm closing this issue. Should the problem return, open a new issue.

**Comment by paales** [comment]
@dorshinar The problem seemed to be in the GITHUB_REF which isn't an actual branch when running a PR. By checking for GITHUB_HEAD_REF first we solve the issue.

```
const branch = process.env.GITHUB_HEAD_REF || process.env.GITHUB_REF.match(/(?<=refs\/heads\/).+/g)[0] 
```

**Comment by dorshinar** [comment]
@paales Thanks for the clarification!

**Comment by josephwynn-sc** [comment]
I just wanted to add my learnings to this issue in case anyone has the same problem: I was triggering my workflow on the `deployment` event, but this event doesn't always contain a ref name - just a commit hash. I tried poking around GitHub API to see if there was a way to get this action to work with commits, but I couldn't find anything that looked like it would work.

The solution for me was to run my workflow on `push` instead, and rely on this action waiting for the deployment to finish.
