### ISSUE TITLE
3rd party app request.

### ISSUE THREAD

**Issue by bbourn** [dorshinar/get-deployment-url#10]
I am trying to use this with a private repo under our company group.

I am getting 
```
Cannot read property 'target' of null
```

I think because the gql query is coming back empty because it can't see the repo.

When I checked it with GitHub GraphQL API Explorer.  That is the error I got.

I had to go to my account that I pass the token for, and under Applications -> Authorized OAuth Apps, "request" Organization access.  

I am thinking they updated they way they do things, and not sure how to proceed.

What do you think?

**Comment by dorshinar** [comment]
Sorry for the delay in response.
I'm not sure what the best way to proceed is - I'm using this action with a public repo, for which I have complete control. 
The action should work as long as you can query for the data. If your can't get it from the explorer, the action won't be able to as well. 
I suggest taking a look at what permissions you have, you might need additional scopes. 
This may give you some answers: [https://docs.github.com/en/graphql/guides/forming-calls-with-graphql](https://docs.github.com/en/graphql/guides/forming-calls-with-graphql)
