### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by acron0** [dorshinar/get-deployment-url#15]
![image](https://user-images.githubusercontent.com/812199/134501838-14718583-65ab-4f34-b201-99e1c468de41.png)

Getting this when I try to get the deployment URL :(

**Comment by acron0** [comment]
So it's fixed?

**Comment by dorshinar** [comment]
No
I probably missed this issue and it was silent for a long time.
If this is still happening with the latest version, can you please run the following query in the [GitHub API Explorer](https://docs.github.com/en/graphql/overview/explorer) and see if it returns anything:
```graphql
query($repo: String!, $owner: String!, $branch: String!) {
  repository(name: $repo, owner: $owner) {
    ref(qualifiedName: $branch) {
      target {
        ... on Commit {
          deployments(last: 1) {
            edges {
              node {
                latestStatus {
                  environmentUrl
                }
              }
            }
          }
        }
      }
    }
  }
}
```
