### ISSUE TITLE
set-output command will be deprecated soon

### ISSUE THREAD

**Issue by andobolocco** [dorshinar/get-deployment-url#24]
got this warning when running this action:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

![image](https://user-images.githubusercontent.com/842842/202187670-8d0a1334-406e-41bf-ac19-214b8282690b.png)

**Comment by dorshinar** [comment]
Thanks for the heads up!
I'll try to take a look at it soon. If you have some time I'd really appreciate a PR

**Comment by jeremylorino** [comment]
@dorshinar 
> Thanks for the heads up! I'll try to take a look at it soon. If you have some time I'd really appreciate a PR

Please see #28 for the fix
