### ISSUE TITLE
Add vercel and nextjs descriptions to README

### ISSUE THREAD

**Issue by paales** [dorshinar/get-deployment-url#4]
I guess the main purpose of this action is to get the deployment URL of a nextjs installation deployed on Vercel. Might be interesting to write some additional documentation for that. Might also be interesting to reference the blogpost you've written about it :)

**Comment by dorshinar** [comment]
Actually it is used with a Gatsby site on Vercel, but the principal is the same. I'm still planning on writing a more elaborate post about integrating GitHub actions with the GitHub API, so I'll link to it when it's done.

**Comment by paales** [comment]
Ahh, I'm using it with NextJS, so it's really more about Vercel :)
